### ISSUE TITLE
Craft 4 compatibility

### ISSUE THREAD

**Issue by eddiedale** [shornuk/craft-plausible#10]
Hi! Thanks for maintaining this very cool plugin! Do you have any plans on updating for Craft 4?

**Comment by shornuk** [comment]
Yes, planning on getting an update out within the next week or two 👍

**Comment by shornuk** [comment]
Craft 4 compatibility added and just released. Please report any issues. Thanks.

**Comment by eddiedale** [comment]
You're a champ Sean, Thanks! 💯

**Comment by sebastianbayer** [comment]
Currently I can't install the plugin. 😢 I'm using the latest Craft CMS version (4.3.4). Can we expect a fix for this or should we rather downgrade to the last working version? If yes, which one would that be? Thanks!

**Comment by shornuk** [comment]
Gonna need to give a few more details, I'm afraid.

**Comment by sebastianbayer** [comment]
Weird…last week the install button was disabled…maybe it was a Craft problem/bug…now I could install 👍 Thanks for this plugin!
