### ISSUE TITLE
Support for self-hosted Plausible

### ISSUE THREAD

**Issue by jessedobbelaere** [shornuk/craft-plausible#11]
I'm using the self-hosted version (https://plausible.io/docs/self-hosting) so I'm looking for a way to configure the base url. 
I had a quick look and it seems the `PlausibleService.php` would need changes to support an optional custom domain.

```php
$format = 'https://plausible.io/api/v1/stats/realtime/visitors?site_id=%1$s';
```

Should be able to call `https://mycustomplausibledomain.com/api/...` instead of the hosted `https://plausible.io/api` if a custom domain was entered in the settings.

Any plans on adding this? I might check to make a pull request

**Comment by shornuk** [comment]
Hi. I'll take a look. Should be able to make this configurable.

**Comment by shornuk** [comment]
@jessedobbelaere any chance you can share details for your self hosted version? Would like to test, but not set up with a self hosted instance.

**Comment by jessedobbelaere** [comment]
Hi @shornuk thanks for taking the team to develop this 🙏 
I just run the docker version of Plausible on a digitalocean droplet, and use it on a subdomain. 

For example, I can call the API in the same way as the hosted Plausible. The API key is set up inside the Plausible interface (same way as in the hosted version).

```
curl "https://pa.jessedobbelae.re/api/v1/stats/timeseries?site_id=jessedobbelae.re&period=6mo" \
     -H 'Authorization: Bearer XXX'
```

So I think the only difference is that the base url changes from `https://plausible.io/` to _<any custom domain configured in settings>_

On the docs (https://plausible.io/docs/self-hosting-configuration#server) I can see that a self-hosted instance can be configured with a specific BASE_URL and PORT. But a user of craft-plausible should just be able to configure a custom base url (https://myplausibleinstance.website.com or https://supersecret.io:5858) in the settings.

**Comment by readtedium** [comment]
I would also welcome this, thanks for looking into it

**Comment by CreateSean** [comment]
I see that this is working with self hosted, but in the self hosted plausing I do not see an option to generate an API key and without the api key am unable to save the settings for the plugin.

I checked the plausible docs but cannot find any info about api keys for self hosted.

**Comment by jessedobbelaere** [comment]
@CreateSean On the self-hosted page `/settings` (top-right menu -> settings) you can generate an API key. It's not project-specific, but it works fine...

**Comment by CreateSean** [comment]
@jessedobbelaere Thank you. 

I've added the api key and site id (mydomain.com) and updated the base url and now when I add a widget I get this error when visiting the CP dashboard.  There is no way to resolve this except by importing an db backup:

This happens locally - haven't tried on the live site yet.

![image](https://github.com/shornuk/craft-plausible/assets/6899490/c6b5387d-19e1-4eee-ad2c-ea242c3f3acb)

**Comment by jessedobbelaere** [comment]
Not sure what happens, probably an invalid response. But you could edit the file in your vendor folder and put a `var_dump($e);die();` in the catch statement. Or try the API call manually to see if it defitely returns JSON data, for example:

```
curl "https://baseurl/api/v1/stats/timeseries?site_id=mywebsite.com" -H 'Authorization: Bearer APIKEY'
```

**Comment by CreateSean** [comment]
@jessedobbelaere 

```
I tried the curl statement using the local domain and the live domain and both failed with:

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it.
```
I also added the dump statement to line 149 but didn't notice any change.

**Comment by jessedobbelaere** [comment]
Try with `curl --insecure` but it seems like an invalid certificate on your self-hosted instance...

**Comment by CreateSean** [comment]
Yeah that works on the live site - weird because I do have a let's encrypt ssl up and running. I removed it and re-added the curl without insecure failed but once I added --insecure it worked.

Strange.
