### ISSUE TITLE
Compatible with Plausible 2.0.0?

### ISSUE THREAD

**Issue by bencroker** [shornuk/craft-plausible#14]
Hoping to update Plausible to version [2.0.0](https://github.com/plausible/analytics/releases/tag/v2.0.0). Has this plugin been tested to work with it yet?

**Comment by shornuk** [comment]
Not yet no. Haven't had much time on this lately. Hopefully in the coming week or two.

**Comment by bencroker** [comment]
Thank you!

**Comment by angelokeirsebilck** [comment]
I've just updated my self-hosted Plausible to plausible/analytics:latest and as far as I know I dit not encounter any problems yet.

**Comment by bencroker** [comment]
I updated and all looks well!

**Comment by shornuk** [comment]
Great. I've not got self hosting set up, so thanks for the feedback. 👍
