### ISSUE TITLE
Overview - Error message

### ISSUE THREAD

**Issue by okay-type** [shornuk/craft-plausible#3]
Hi, 

Just set this up and am getting this error message in the Overview widget.  

The metric `visit_duration ` is not recognized. Find valid metrics from the documentation: https://plausible.io/docs/stats-api#get-apiv1statsbreakdown

Assuming this is because it's a brand new installation, but it should probbbabably have a nice message rather than throw an error.

Running Craft Pro 3.5.17.1 fwiw

Cheers,
Jackson

**Comment by shornuk** [comment]
Plausible recently updated their api, I've got an update 95% ready and hope to release it within the next day which should bring it all up to date. 👍

**Comment by shornuk** [comment]
@okay-type just pushed a new release that should fix this. 201dfeead87e06aa52e65bc598364cd03cf476a2 - Thanks.
