### ISSUE TITLE
wrong composer package name in README

### ISSUE THREAD

**Issue by bencresty** [shornuk/craft-plausible#4]
Hi, the package name in the README cannot be found by Composer. According to packagist the package name is

``` text
shornuk/craft-plausible
```

But in the README it is missing the `craft-`-part, as it says
``` text
composer require shornuk/plausible
```

https://packagist.org/packages/shornuk/craft-plausible

**Comment by shornuk** [comment]
Nice catch! Thanks @bencresty, have updated now.

**Comment by bencresty** [comment]
@shornuk btw, probably a silly question, but where can we get that API key? I don't see it nowhere in my Plausible account. Is it so new that it's not public yet, or am I missing something? Thanks
